In [5]:
import numpy as np

In [6]:
# For example, you can create an array from a regular 
# Python list or tuple using the array function. The 
# type of the resulting array is deduced from the type 
# of the elements in the sequences.

In [7]:
a = np.array([2, 4, 5])

In [8]:
a

array([2, 4, 5])

In [9]:
a.dtype

dtype('int32')

In [10]:
 b = np.array([1.2, 5.3 ,5])

In [12]:
b.dtype

dtype('float64')

In [13]:
# A frequent error consists in calling array with multiple
# numeric arguments, rather than providing a single list of
# numbers as an argument.
# >>> a = np.array(1,2,3,4)    # WRONG
# >>> a = np.array([1,2,3,4])  # RIGH

In [14]:
b = np.array([(1.4,2,3), (5,6,7)])

In [15]:
b

array([[1.4, 2. , 3. ],
       [5. , 6. , 7. ]])

In [16]:
# The type of the array can also be explicitly specified at creation time:
c = np.array( [ [1,2], [3,4] ], dtype=complex )

In [17]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])