In [5]:
import numpy as np

In [6]:
# For example, you can create an array from a regular 
# Python list or tuple using the array function. The 
# type of the resulting array is deduced from the type 
# of the elements in the sequences.

In [7]:
a = np.array([2, 4, 5])

In [8]:
a

array([2, 4, 5])

In [9]:
a.dtype

dtype('int32')

In [10]:
#  b = np.array([1.2, 5.3 ,5])

In [12]:
b.dtype

dtype('float64')

In [13]:
# A frequent error consists in calling array with multiple
# numeric arguments, rather than providing a single list of
# numbers as an argument.
# >>> a = np.array(1,2,3,4)    # WRONG
# >>> a = np.array([1,2,3,4])  # RIGH

In [25]:
# b = np.array([(1.4,2,3), (5,6,7)])

In [26]:
b

array([[1.4, 2. , 3. ],
       [5. , 6. , 7. ]])

In [16]:
# The type of the array can also be explicitly specified at creation time:
c = np.array( [ [1,2], [3,4] ], dtype=complex )

In [17]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [18]:
# Often, the elements of an array are originally unknown,
# but its size is known. Hence, NumPy offers several functions
# to create arrays with initial placeholder content.
# These minimize the necessity of growing arrays, an expensive operation.

In [19]:
# The function zeros creates an array full of zeros,
# the function ones creates an array full of ones,
# and the function empty creates an array whose initial
# content is random and depends on the state of the memory.
# By default, the dtype of the created array is float64.

np.zeros( (3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones( (2,3,4), dtype=np.int16 ) # dtype can also be specifed

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [31]:
np.empty( (2,3) ) ## uninitialized, output may vary

array([[1.4, 2. , 3. ],
       [5. , 6. , 7. ]])

In [32]:
# To create sequences of numbers, NumPy provides a 
# function analogous to range that returns arrays instead of lists.

In [36]:
np.arange( 10, 39, 5)

array([10, 15, 20, 25, 30, 35])

In [38]:
np.arange( 0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [39]:
# When arange is used with floating point arguments, 
# it is generally not possible to predict the number 
# of elements obtained, due to the finite floating point
# precision. For this reason, it is usually better to use
# the function linspace that receives as an argument the 
# number of elements that we want, instead of the step:
from numpy import pi

In [47]:
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])