In [2]:
import numpy as np

In [3]:
# Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [4]:
a = np.array( [20,30,40,50] )

In [9]:
b = np.arange(4)

In [10]:
b

array([0, 1, 2, 3])

In [11]:
c = a-b

In [12]:
c

array([20, 29, 38, 47])

In [13]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [14]:
a<35

array([ True,  True, False, False])

In [46]:
# Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays.
# The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

In [20]:
A = np.array( [[1,1],
               [0,1]])

In [21]:
B = np.array( [[2,0], 
               [3,4]])

In [23]:
A*B # elementwise product

array([[2, 0],
       [0, 4]])

In [24]:
 A @ B # matrix product

array([[5, 4],
       [3, 4]])

In [26]:
A.dot(B) # another matrix product

array([[5, 4],
       [3, 4]])

In [47]:
# Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [27]:
a = np.ones((2,3), dtype=int)

In [28]:
b = np.random.random((2,3))

In [29]:
a *= 3

In [30]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [31]:
b += a

In [33]:
b

array([[3.73020501, 3.98380273, 3.2782278 ],
       [3.08644416, 3.52704758, 3.62320554]])

In [35]:
a += b  # b is not automatically converted to integer type

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [48]:
# When operating with arrays of different types, the type of the resulting array corresponds
# to the more general or precise one (a behavior known as upcasting).

In [38]:
from numpy import pi

In [36]:
a = np.ones(3, dtype=np.int32)

In [39]:
b = np.linspace(0,pi,3)

In [40]:
b.dtype.name

'float64'

In [41]:
c = a+b

In [42]:
c

array([1.        , 2.57079633, 4.14159265])

In [43]:
d = np.exp(c*1j)

In [44]:
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [45]:
d.dtype.name

'complex128'

In [49]:
# Many unary operations, such as computing the sum of all the elements in the array,
# are implemented as methods of the ndarray class.

In [50]:
a = np.random.random((2,3))

In [51]:
a

array([[0.55559971, 0.41755036, 0.0914986 ],
       [0.85196262, 0.07937239, 0.52426036]])

In [52]:
a.sum()

2.5202440500062853

In [53]:
a.min()

0.07937239199023294

In [54]:
a.max()

0.8519626216829216

In [55]:
# By default, these operations apply to the array as though it were a list of numbers,
# regardless of its shape. However, by specifying the axis parameter you can apply an 
# operation along the specified axis of an array:

In [56]:
b = np.arange(12).reshape(3,4)

In [57]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
 b.sum(axis=0)                            # sum of each column

array([12, 15, 18, 21])

In [59]:
b.min(axis=0)

array([0, 1, 2, 3])

In [60]:
b.min(axis=1)

array([0, 4, 8])

In [61]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)