In [1]:
import numpy as np

In [2]:
# When operating and manipulating arrays, their data is sometimes copied into a new
# array and sometimes not. This is often a source of confusion for beginners. There are three cases:

In [3]:
# No Copy at All
a = np.arange(12)

In [6]:
b = a  # no new object is created

In [7]:
b is a # a and b are two names for the same ndarray object

True

In [8]:
b.shape = 3,4    # changes the shape of a

In [9]:
a.shape

(3, 4)

In [10]:
# Python passes mutable objects as references, so function calls make no copy.
def f(x):
    print(id(x))

In [11]:
id(a)

177926296

In [12]:
f(a)

177926296


In [13]:
# View or Shallow Copy

In [14]:
# Different array objects can share the same data. The view method creates a new array object that looks at the same data.
c = a.view()

In [15]:
c is a

False

In [17]:
c.base is a  # c is a view of the data owned by a

True

In [18]:
c.flags.owndata

False

In [19]:
c.shape = 2,6 # a's shape doesn't change

In [20]:
a.shape

(3, 4)

In [30]:
c[0,4] = 1234                      # a's data changes

In [31]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [33]:
# Slicing an array returns a view of it:
s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"

In [34]:
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10

In [35]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [36]:
# Deep Copy
# The copy method makes a complete copy of the array and its data.

In [37]:
d = a.copy()                          # a new array object with new data is created

In [38]:
d is a

False

In [39]:
d.base is a

False

In [40]:
d[0,0] = 9999

In [41]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [42]:
# Sometimes copy should be called after slicing if the original array is not required anymore. 
# For example, suppose a is a huge intermediate result and the final result b only contains a small
# fraction of a, a deep copy should be made when constructing b with slicing:

In [43]:
a = np.arange(int(1e8))

In [44]:
b = a[:100].copy()

In [45]:
del a  # the memory of ``a`` can be released.