In [1]:
import numpy as np

In [2]:
# Changing the shape of an array
# An array has a shape given by the number of elements along each axis:

In [3]:
a = np.floor(10*np.random.random((3,4)))

In [4]:
a

array([[2., 6., 8., 8.],
       [0., 5., 0., 3.],
       [8., 1., 6., 9.]])

In [5]:
a.shape

(3, 4)

In [6]:
# The shape of an array can be changed with various commands. Note that the following three commands
# all return a modified array, but do not change the original array:

In [7]:
a.ravel()  # returns the array, flattened

array([2., 6., 8., 8., 0., 5., 0., 3., 8., 1., 6., 9.])

In [8]:
a.reshape(6,2)  # returns the array with a modified shape

array([[2., 6.],
       [8., 8.],
       [0., 5.],
       [0., 3.],
       [8., 1.],
       [6., 9.]])

In [10]:
a.T  # returns the array, transposed

array([[2., 0., 8.],
       [6., 5., 1.],
       [8., 0., 6.],
       [8., 3., 9.]])

In [11]:
a.T.shape

(4, 3)

In [12]:
a.shape

(3, 4)

In [13]:
# The order of the elements in the array resulting from ravel() is normally “C-style”,
#     that is, the rightmost index “changes the fastest”, so the element after a[0,0] is a[0,1]. 
#     If the array is reshaped to some other shape, again the array is treated as “C-style”. NumPy
#     normally creates arrays stored in this order, so ravel() will usually not need to copy its argument,
#     but if the array was made by taking slices of another array or created with unusual options, it may
#     need to be copied. The functions ravel() and reshape() can also be instructed, using an optional argument,
#     to use FORTRAN-style arrays, in which the leftmost index changes the fastest.

#     The reshape function returns its argument with a modified shape, whereas the
#     ndarray.resize method modifies the array itself:

In [14]:
a

array([[2., 6., 8., 8.],
       [0., 5., 0., 3.],
       [8., 1., 6., 9.]])

In [18]:
a.resize((2,6))

In [19]:
a

array([[2., 6., 8., 8., 0., 5.],
       [0., 3., 8., 1., 6., 9.]])

In [20]:
# If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

In [21]:
a.reshape(3,-1)

array([[2., 6., 8., 8.],
       [0., 5., 0., 3.],
       [8., 1., 6., 9.]])

In [23]:
# Stacking together different arrays
#     Several arrays can be stacked together along different axes:

In [24]:
a = np.floor(10*np.random.random((2,2)))

In [25]:
a

array([[3., 5.],
       [7., 1.]])

In [26]:
 b = np.floor(10*np.random.random((2,2)))

In [27]:
b

array([[6., 8.],
       [9., 7.]])

In [28]:
np.vstack((a,b))

array([[3., 5.],
       [7., 1.],
       [6., 8.],
       [9., 7.]])

In [29]:
np.hstack((a,b))

array([[3., 5., 6., 8.],
       [7., 1., 9., 7.]])

In [30]:
# The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:

In [31]:
from numpy import newaxis

In [32]:
np.column_stack((a,b))     # with 2D arrays

array([[3., 5., 6., 8.],
       [7., 1., 9., 7.]])

In [35]:
a = np.array([4.,2.])

In [37]:
b = np.array([3.,8.])

In [38]:
np.column_stack((a,b))     # returns a 2D array

array([[4., 3.],
       [2., 8.]])

In [39]:
np.hstack((a,b))           # the result is different

array([4., 2., 3., 8.])

In [40]:
a[:,newaxis]               # this allows to have a 2D columns vector

array([[4.],
       [2.]])

In [41]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [42]:
np.hstack((a[:,newaxis],b[:,newaxis]))   # the result is the same

array([[4., 3.],
       [2., 8.]])

In [43]:
# On the other hand, the function row_stack is equivalent to vstack for any input arrays. 
# In general, for arrays of with more than two dimensions, hstack stacks along their second axes,
# vstack stacks along their first axes, and concatenate allows for an optional arguments giving the
# number of the axis along which the concatenation should happen.

# Note

# In complex cases, r_ and c_ are useful for creating arrays by stacking numbers 
# along one axis. They allow the use of range literals (“:”)

In [44]:
# Splitting one array into several smaller ones
#     Using hsplit, you can split an array along its horizontal axis, either by
#     specifying the number of equally shaped arrays to return, or by specifying
#     the columns after which the division should occur:

In [45]:
a = np.floor(10*np.random.random((2,12)))

In [46]:
a

array([[0., 8., 6., 3., 9., 5., 7., 3., 4., 1., 9., 5.],
       [9., 2., 1., 7., 0., 6., 3., 6., 3., 0., 6., 2.]])

In [47]:
np.hsplit(a,3)   # Split a into 3

[array([[0., 8., 6., 3.],
        [9., 2., 1., 7.]]), array([[9., 5., 7., 3.],
        [0., 6., 3., 6.]]), array([[4., 1., 9., 5.],
        [3., 0., 6., 2.]])]

In [48]:
np.hsplit(a,(3,4)) # Split a after the third and the fourth column

[array([[0., 8., 6.],
        [9., 2., 1.]]), array([[3.],
        [7.]]), array([[9., 5., 7., 3., 4., 1., 9., 5.],
        [0., 6., 3., 6., 3., 0., 6., 2.]])]