In [1]:
import numpy as np

In [4]:
# NumPy provides familiar mathematical functions such as sin, cos, and exp. 
# In NumPy, these are called “universal functions”(ufunc). Within NumPy, these
# functions operate elementwise on an array, producing an array as output.

In [2]:
B = np.arange(3)

In [3]:
B

array([0, 1, 2])

In [5]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [6]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [7]:
C = np.array([2., -1., 4.])

In [9]:
np.add(C, B)

array([2., 0., 6.])

In [10]:
# Indexing, Slicing and Iterating
# One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [21]:
a = np.arange(10)**3

In [12]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [13]:
a[2]

8

In [14]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [15]:
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000

In [16]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [17]:
 a[ : :-1]  

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [22]:
for i in a:
        print(i**(1/3.))

0.0
1.0
2.0
3.0
3.9999999999999996
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [23]:
# Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [24]:
def f(x,y):
    return 10*x+y

In [25]:
b = np.fromfunction(f,(5,4),dtype=int)

In [26]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [29]:
b[2,3]

23

In [30]:
b[0:5, 1]    # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [31]:
 b[ : ,1]    # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [32]:
b[1:3, : ]   # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [33]:
b[-1]     # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

In [ ]:
# The expression within brackets in b[i] is treated as an i followed by as many instances of :
#     as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i,...].

# The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example,
# if x is an array with 5 axes, then

# x[1,2,...] is equivalent to x[1,2,:,:,:],
# x[...,3] to x[:,:,:,:,3] and
# x[4,...,5,:] to x[4,:,:,5,:].

In [36]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
                [[100,101,102],
                [110,112,113]]])

In [38]:
c.shape

(2, 2, 3)

In [39]:
c[1,...] # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [40]:
c[...,2]  # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

In [41]:
# Iterating over multidimensional arrays is done with respect to the first axis:

In [42]:
for row in b:
     print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [43]:
# However, if one wants to perform an operation on each element in the array,
# one can use the flat attribute which is an iterator over all the elements of the array:

In [44]:
for element in b.flat:
     print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
